version: '3.5'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=4000
      - HOST=0.0.0.0
    volumes:
      - .:/app
      - node_modules:/app/node_modules/
    ports:
      - "4000:4000"
networks:
  default:
    external:
      name: boxify

volumes:
  node_modules:
